name: release artifact
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_dist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@739bfe42ca9233c5e6aca07c1a25a9d34aca49b0 # v6.0.7
        with:
          version: 11
      - name: pnpm install, build:dist
        env:
          SDK_API_KEY: ${{ secrets.SDK_API_KEY }}
          DEFAULT_ENDPOINT: ${{ secrets.DEFAULT_ENDPOINT }}
        run: |
          pnpm install
          pnpm build:dist

      - name: zip dist
        run: |
          cd dist
          zip release atj.*

      - name: Create release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/release.zip
          asset_name: atj.zip
          asset_content_type: application/zip
